name: Pull-Request CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        if [[ $GITHUB_BASE_REF ]]
        then
          export NX_BASE=remotes/origin/$GITHUB_BASE_REF
        else
          export NX_BASE=$(git rev-parse HEAD~1)
        fi
        echo "Base => $NX_BASE"
        # npm run format:check -- --base=$NX_BASE
        # npm run affected:lint -- --base=$NX_BASE
        npm run affected:build -- --base=$NX_BASE
        npm run affected:test -- --base=$NX_BASE
      env:
        CI: true
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.2.6
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_COVERAGE_REPORT_ID }}
      with:
        coverageCommand: "npm run client:coverage"
